import 'package:gwent/controller/states/abstract_state_controller.dart';
import 'package:gwent/models/board/board.dart';
import 'package:gwent/models/observer/observer.dart';
import 'package:gwent/models/observer/subject.dart';
import 'package:gwent/models/players/abstract_player.dart';

abstract class AbstractController {
  void setState(AbstractStateController aState);
  void assignPlayer1(AbstractPlayer player);
  void assignPlayer2(AbstractPlayer player);
  void assignObserver(Observer o);
  void assignBoard(Board board);
  Board getBoard();
  AbstractPlayer getPlayer1();
  AbstractPlayer getPlayer2();
  bool getIsFinish();
  void resetGame();
  void loose(Subject o);
  void handleState();
  void start();
  void roundInit();
  void player1Turn();
  void player2Turn();
  void playCardP1();
  void playCardP2();
  void playCardsP1();
  void playCardsP2();
  void finishRound();
  void nextRound();
  void finishGame();
  bool isStart();
  bool isRoundInit();
  bool isPlayer1Turn();
  bool isPlayer2Turn();
  bool isPlayCardP1();
  bool isPlayCardP2();
  bool isPlayCardsP1();
  bool isPlayCardsP2();
  bool isFinishRound();
  bool isNextRound();
  bool isFinishGame();
}